highlightjs/highlightjs-solidity

solidity.js

This pull request attempts to address the issues I pointed out in #2.  I know @abcoathup has a parallel one (#4) to also do that, but I had some problems with that one and I also finally had time to sit down and do this myself.  Warning: I haven't really tested this and am not entirely certain I'm using highlight.js correctly.  I would appreciate review by someone who knows the library better.
So, changes made here:
1. Singular time literals have been removed.
2. Fixed-point types have been added!  Obviously I had to autogenerate these.  (Although now that I think about it, maybe these should have been a separate mode?  Oh well.)  Apologies for the old-style Javascript, but everything else here seems to be written in old-style Javascript, so I decided to stick to that, since I don't know …

Update for 0.5.x, add other missing things, other various fixes

---

solidity.js

This PR just has some really minor fixes.  Originally I had intended to use it to make a fix to string escapes, but it turns out I misunderstood how those work and actually those are completely fine, nothing needs fixing there.  So I just fixed some other stuff I noticed in the meantime.
Anyway, the PR does the following three things:
1. Adds `is` to the list of keywords.  We all missed this, it seems.  (It was in the section about contract titles, but I figured it should be in the main list of keywords too.)
2. Restyles pragmas as `meta`.
3. Adds strings to pragmas (as in `pragma experimental "v0.5.0"`, back when that was a thing) and styles them as `meta-string`.
Ideally the pragma keywords would be styled as `meta-keyword`, but, I didn't see any convenient way to do that and it didn't …

Add is keyword; use meta class for pragmas

---

solidity.js

Solidity 0.5.12 was recently released, and it adds support for the new Istanbul opcodes `selfbalance` and `chainid` in the assembler.  So, I added them here to stay up to date.

Add selfbalance & chainid opcodes

---

solidity.js

This PR just quickly adds `from` and `as` to the main list of keywords.  This isn't really strictly necessary, since they're already listed in the keywords for the `import` environment, but I thought it would be good to include them for completeness/consistency.

Add from and as keywords to main keyword list

---

solidity.js

This PR is intended to re-fix issue #9.  It turned out that the original fix was insufficient, because Firefox would fail to even *parse* the script if it contained negative lookbehind in regular expression literals.  As such, this PR replaces the one such literal with a string literal (which, yes, means doubled backslashes); I didn't bother wrapping it in `new RegExp(...)` because highlightjs handles that automatically.
(Really @frangio deserves credit for noticing this and realizing the fix, but since I had some free time figured I'd actually do it and PR this.)

Replace negative-lookbehind regexp with string for Firefox

---

solidity.js

Welp, it seems Solidity 0.6.0 is here sooner than I expected!  Fortunately it didn't include as many changes as originally planned...
I've updated the syntax in the following ways:
* Added the new keywords `abstract`, `virtual`, `override`, `fallback`, `receive`, `try`, and `catch`
* Added the new assembly keyword `leave`
* Added `address` to the list of generic members?  Not sure how that'll play out exactly but added it FWIW
* Added `Error` as a builtin; not sure that's exactly the right category for it but I thought it made sense to add and that seemed like the closest thing
* Altered the regular expressions for hex strings so that they are now required to be of even length, and to allow an optional single underscore between each byte

Update syntax for Solidity 0.6.0

---

solidity.js

This PR contains updates for Solidity 0.6.2.  Specifically:
1. The literals `true` and `false` are now allowed in assembly mode.
2. I added `gas`,`value`, and `salt` as builtins due to the new function-call syntax?  I'm not sure builtin is really the right place for these, but I couldn't figure out what was better... I mean they're not keywords, surely?  (Like, pretty sure you can still use them as variable names, e.g.)  IDK, if anyone has a better idea, please suggest it.  (I mean ideally we'd only highlight them in context, but that seems really hard!)
(Also, in my previous PR, I accidentally used tabs instead of spaces at one point... oops!  Fixed here.)

Updates for Solidity 0.6.2

---

solidity.js

Solidity 0.6.5 adds the `immutable` keyword, so, here's a PR to add it to the highlighting.

Add immutable keyword from Solidity 0.6.5

---

solidity.js

I didn't realize this before, but, in Solidity 0.6.0, inline assembly was expanded to allow Yul, not just old-style inline assembly.  This adds three more builtin functions.
Also, it turns out that inline assembly, even before it was Yul, had some keywords I didn't realize.  So I've added those too.

Add Yul keywords to assembly keywords

---

solidity.js

One more quick change, I've added `interfaceId` (alongside `runtimeCode` and etc) now that it's been added in Solidity 0.6.7.
Also, that line was getting kind of ridiculously long, so I split it up a bit...

Add highlighting for type(I).interfaceId

---

solidity.js

Solidity 0.6.8 adds `type(T).min` and `type(T).max`, so this PR adds highlighting for `min` and `max` when used as members.

Add highlighting for type(T).min & type(T).max

---

solidity.js

So, looks like I made a mistake earlier in adding `datasize`, `dataoffset`, and `datacopy`.  These are Yul functions, yes, but they're not actually available in the dialect of Yul that is Solidity assembly.  For the same reason, I'm not adding any of the Yul keywords `object`, `code`, or `data`, or the Yul functions `setimmutable` or `loadimmutable`, as none of these are actually available in the Solidity assembly Yul dialect.
Sorry about that.  It's confusing how Yul has "dialects"!

Remove Yul functions that don't exist in Solidity assembly

---

solidity.js

Solidity 0.6.11 is out and adds the `gwei` unit, so I've added that to the list of units.

Add gwei unit

---

solidity.js

This PR updates the syntax to cover Solidity 0.7.0.  This means two things:
1. First, there's now the `variable.slot` and `variable.offset` notation in assembly; previously it was `variable_slot` and `variable_offset`.  You'll notice I've made this a separate mode from the old style; that's because I suspect the new style might get expanded soon with more possibilities, whereas the old one won't.
2. I've changed the string literal classes from the builtin ones to new custom ones; these as you can see are just slight modifications of the builtin ones, to allow an optional `unicode` prefix before the string.

Update syntax for Solidity 0.7.0

---

solidity.js

Specifically:
1. In the assembly section, I've added `length` to the list of generic members, since one can now do `x.length` in assembly where `x` is a calldata variable of a dynamically-sized type.
2. I added the `abicoder` pragma.  Following the example of how we handle the different experimental pragmas, I added `v1` and `v2` as builtins; not sure if that's the best place for them (I also considered literals, or treating them as numbers), but I guess it's probably fine?

Update syntax for Solidity 0.7.5

---

solidity.js

Well, and for 0.7.6, but that added no new syntax.
Additions:
* `unchecked` keyword
* `chainid` as builtin member of `block`
* `code` and `codehash` as generic builtin members
I did *not* add `Panic` as a builtin like we have for `Error` because catching those isn't actually possible yet, meaning there's nowhere in the actual language syntax where it's special.  I figure adding that can wait until `Panic` is an actual part of the language syntax.
I think that covers it?

Update syntax for Solidity 0.8.0

---

solidity.js

Solidity 0.8.1 is out and it is now possible to catch panics, so I added `Panic` as a builtin, alongside error.  Also I deleted my comment about not being sure this is the right place because (assuming custom errors are eventually coming) it sure seems like it is.

Add Panic to list of builtins alongside Error

---

solidity.js

Syntax updates for Solidity 0.8.4:
1. I've promoted `revert` from a builtin to a keyword.  Really it's both now, but I figure keyword wins?
2. I've added `error` as a keyword.
3. I've added the new builtin `bytes.concat`.
4. I was going to add hex strings in assembly, but it turns out we actually already had those even though they apparently didn't exist previously! :P

Update syntax for Solidity 0.8.4

---

solidity.js

In a few places, rather than relying on keywords and lexemes, we have regular expressions that begin with certain words.  However, we didn't do anything to check that those words are occurring after a word-break.
For `gas`/`value`/`salt` I did this properly and also checked for dollar signs if negative lookbehind is available.  (I also split that up a bit so it's easier to add more in the future if any more are ever added.)
For `unicode` and `hex`, I did things the lazy way and just used `\b`; after all, if you add something to the beginning of these, it's no longer valid syntax in the first place, so I think that's probably fine, assuming we're mostly concerned with valid syntax.  But, obviously, I can go back and change that if this is considered to be a problem.

Require word-breaks before gas, value, salt, etc

---

solidity.js

Just noticed that I'd totally missed updating this.  Obviously `fallback`, `receive`, and `error` all got added to the list of keywords, but not here.  So I've added them here now.  (Obviously `error` isn't actually a type of function declaration, but it makes sense to highlight it the same way, and `event` is already included here for the same reason.)

Add fallback, receive, error as types of function declarations

---

solidity.js

Sorry, one more fix here: I realized the colon itself shouldn't be really included in the `gas`/`value`/`salt` highlighting, so I changed the `:` to `(?=:)` (a lookahead assertion) to exclude it from the match.

Exclude colon from special parameters

---

solidity.js
test.js

This PR makes it so that this package provides Yul highlighting in addition to Solidity highlighting.  Now, you may say, isn't just Yul just Solidity assembly?  Well, yes, but it has a few additional keywords and builtins.  I didn't want to add those to our list of keywords and builtins in Solidity assembly, though, because, well, they didn't exist there.  So instead I made Yul separate and made it so that the package will register Yul as a second language in addition to Solidity.  (@joshgoebel, I hope that's OK with all the transition stuff; I didn't want to make a separate `highlight-yul` package, because, well, it would largely consist of copied code.)
This entailed moving a bunch of the setup code outside the `hljsDefineSolidity` function so that it could be used by both Solidity and …

Add Yul and register it in addition to Solidity

---

solidity.js
test.js

This PR adds highlighting for the `verbatim` family of assembly builtins introduced in 0.8.5.  Rather than handling these by the crazy way I handled fixed-point types (I should probably redo those at some point...) I just used a regular expression.  So this means it gets its own mode rather than just being a keyword.
Also, while I was at it, I added a second commit to require that numbers are followed by a word break, since we didn't have that previously.

Syntax update for Solidity 0.8.5: Add `verbatim` builtin in assembly

---

solidity.js
test.js

This PR adds operator and punctuation highlighting for Solidity and Yul.  Well -- I did some of this in maybe an iffy way, but, well, obviously it can be changed if need be.
For Yul this was straightforward; I added `:=` and `->` as operators, and the obvious things as punctuation.  Arguably `->` should be punctuation, but it seemed worth highlighting as an operator to me.
For Solidity... well, Solidity has a number of operators, but they're all made of the same few characters, so I just checked for those characters.  (So, `=>` will be highlighted as an operator, which makes sense to me.)  For punctuation I put the obvious things.
Except... I did one thing that is maybe kind of off; I put `?` and `:` as punctuation.  Now, `?` should be an operator, right?  It's the ternary operator. …

Add operator and punctuation highlighting

---

solidity.js

Solidity 0.8.7 is out, and it adds `block.basefee` and (in Yul) the `basefee` opcode.  So, this adds highlighting.

Add basefee highlighting for Solidity 0.8.7

---

src/languages/solidity.js

Syntax updates for Solidity 0.8.8:
1. I reclassified `type` as a keyword rather than a builtin, now that it can be used for custom type declarations.
2. I highlighed `wrap` and `unwrap` as builtins when used as a member of something else.  I'm a little uncertain whether this is a good idea; it's possible that `wrap` and `unwrap` functions are sufficiently common that highlighting this would be annoying, and it would be better to just omit highlighting for these. So, uh, please let me know what you think of this.  (@gnidan, I can't add you as a reviewer, but do you have an opinion on this?)

Update syntax for Solidity 0.8.8

---

src/languages/solidity.js

Solidity 0.8.10 adds the syntax `x.address` and `x.selector` when in a Solidity assembly block.  So, adding highlighting for those here.

Add highlighting for .address & .selector in Solidity assembly

---

src/common.js
src/languages/yul.js
test.js

It turns out that `verbatim` currently only exists in standalone Yul, not in Solidity assembly.  So, I restricted it to standalone Yul.  We can revert this commit later if `verbatim` is eventually brought to Solidity assembly, which I believe is [planned](https://github.com/ethereum/solidity/issues/12067).
Also I upped the timeout on the test of `verbatim`, because it was timing out when I ran it locally (probably due to being in a meeting at the time :P ).

Restrict highlighting of verbatim to standalone Yul

---

src/languages/solidity.js

There's only one thing to add: Syntax highlighting for the new builtin function `abi.encodeCall`.

Update syntax highlighting for Solidity 0.8.11

---

src/languages/solidity.js

Solidity 0.8.12 adds the function `string.concat`, so, I've added highlighting for it as a builtin.

Add highlighting for string.concat

---

src/languages/solidity.js

Two updates for this one:
1. I added highlighting for the new `global` keyword.  I guess really this is only a keyword in the context of a `using` declaration, but I highlighted it generally for simplicity?  If you think that's a bad idea though I can change it to only highlight inside a `using` declaration.
2. I allowed string literals inbetween the word `assembly` and the actual assembly-block that follows; this is intended to allow for highlighting in the new syntax `assembly ("memory-safe") { ... }`.  I figured it makes sense to mark such strings as meta strings, rather than ordinary strings?  This doesn't actually make a difference to Truffle's coloring, we color them the same. :P

Syntax updates for Solidity 0.8.13

---

src/common.js
src/languages/solidity.js

Solidity 0.8.18 just came out, and added `block.prevrandao` as well as a `prevrandao` instruction in assembly.  This PR adds highlighting for them.
Note: 0.8.18 also addes the ability to name mapping parameters.  These should likely be highlighted?  It's not obvious to me at the moment what's a good way to do that though so I figured I'd just put up this first.

Add highlighting for prevrandao for Solidity 0.8.18
